### ISSUE TITLE
咨询以下gdb断点调试

### ISSUE THREAD

**Issue by buynowdev** [ultraji/linux-0.12#10]
![image](https://user-images.githubusercontent.com/12961676/116257436-a2a40500-a7a6-11eb-90d0-9ea450f0009f.png)
请教一下这个代码调试界面是gdb + emacs 实现的吗，看gdb list只能简单展示代码

**Comment by ultraji** [comment]
可以试一下gdb的layout命令

**Comment by buynowdev** [comment]
好的 感谢
