### ISSUE TITLE
在执行bochs -f 配置后，未顺利执行

### ISSUE THREAD

**Issue by zhaosonggo** [ultraji/linux-0.12#12]
1. 出现了 “Press <RETURN>  to see SVGA-modes available...." 的提示， 然后输入任意键，都会导致终止

**Comment by ultraji** [comment]
完整操作流程描述 + 错误信息截图

**Comment by zhaosonggo** [comment]
1. 自行修改linux-0.12 的代码，可以顺利编译通过，生成Image文件
2. 模仿您的bochs配置文件构建配置
3. 执行bochs -f
4. 出现这个界面 
![20211206-203138](https://user-images.githubusercontent.com/44077994/144846601-3c5dc5b2-89dc-442b-836e-347a9376bdfa.jpeg)
5. 输入任意键 ，卡死，terminal出现下列字符
![Uploading 20211206-203131.jpeg…]()

**Comment by zhaosonggo** [comment]
![20211206-203131](https://user-images.githubusercontent.com/44077994/144846727-eb0b7093-5b16-47be-9ce5-895304b21f22.jpeg)

**Comment by zhaosonggo** [comment]
您是否有更为便捷的沟通方式，这边还想和你学习更多内核编译的手段

**Comment by zhaosonggo** [comment]
输入任意键后，没有继续走下去，直接就卡住了

**Comment by zhaosonggo** [comment]
我是用您仓库里的是可以运行的，这边想问一下，所用到的hdc.img 有什么特别的地方吗，与使用bximage 生成的一样吗？

**Comment by ultraji** [comment]
wechat: ultraji
