### ISSUE TITLE
编译完之后如何gdb调试呢，这边测试不能

### ISSUE THREAD

**Issue by gt-6** [ultraji/linux-0.12#14]
![image](https://user-images.githubusercontent.com/33917952/162111926-681a2b99-7bec-4364-ad0b-513aebc11b30.png)

./run.sh -m
./run.sh -g
localhost:1234 Connection time out.

**Comment by ultraji** [comment]
./run.sh -m 是什么返回呢

**Comment by gt-6** [comment]
> ./run.sh -m 是什么返回呢

解决了，运行要切换成普通用户运行才可以（root用户./run.sh -m编译，切换成普通用户 ./run.sh -g），建议README.md可以补充一下，少走一些弯路
