### ISSUE TITLE
bug: docker镜像无法编译内核代码

### ISSUE THREAD

**Issue by hoffer32** [ultraji/linux-0.12#4]
运行命令出现如下错误：
```
./run.sh -m
```

![image](https://user-images.githubusercontent.com/16578180/55649018-68a8e480-5814-11e9-808a-ec1c07cfadcb.png)

**Comment by ultraji** [comment]
是把windows的项目文件夹挂载到docker中吗？

**Comment by hoffer32** [comment]
不是，mac的文件夹。
你那边用现在这个镜像还可以编译是吗，那我在容器内clone试试

**Comment by hoffer32** [comment]
已确认在docker中git clone后可编译，thanks @ultraji
